baseURL = "https://parkzonegolf.com/"
languageCode = "ko-kr"
title = "파크존골프"
theme = ""
relativeURLs = false
canonifyURLs = true
enableRobotsTXT = true

[params]
  navbarLogo = "images/logo.png"
  custom_css = ["css/custom.css"]
  canonical = "https://parkzonegolf.com/"
  
[[menu.main]]
  name = "회사 소개"
  url = "#about"
[[menu.main]]
  name = "제품 소개"
  url = "#products"
[[menu.main]]
  name = "설치 문의"
  url = "#contact"
